### ISSUE TITLE
NOT just executeChocoInstaller ?

### ISSUE THREAD

**Issue by gedw99** [united-manufacturing-hub/autok3d#1]
Would you be open to a Linux and Mac options too ?

there is also aqua, which is a cross platform system that can be wrapped and then find and install.
its has a registry and many of the k8 tools are there.
https://github.com/aquaproj/aqua

https://github.com/search?q=repo%3Aaquaproj%2Faqua-registry%20k3d&type=code

**Comment by Scarjit** [comment]
Yes, im open for PR's for any platform, but we are currently not activly developing autok3d anymore.

**Comment by gedw99** [comment]
will contrib on the main repo :)
